"""
agents/base_agent.py
0xFlux4hm AI — VulnAgentRouter

Abstract base class for all sub-agents. Every agent inherits from this class
to ensure consistent logging, ethical disclaimers, safety checks, and output formatting.
"""

import abc
import subprocess
import shlex
import logging
import sqlite3
import datetime
import os
from typing import Optional, Dict, Any

# Ethical disclaimer appended to ALL agent outputs
ETHICAL_DISCLAIMER = (
    "\n" + "─" * 60 + "\n"
    "⚠️  DISCLAIMER: This output is generated by 0xFlux4hm AI for\n"
    "   EDUCATIONAL PURPOSES and AUTHORIZED SECURITY TESTING ONLY.\n"
    "   Unauthorized use against systems you do not own or have\n"
    "   explicit written permission to test is ILLEGAL.\n"
    "   Always comply with all applicable laws and regulations.\n"
    + "─" * 60
)


class BaseAgent(abc.ABC):
    """
    Abstract base class that all VulnAgentRouter agents must extend.

    Provides:
    - Standardized logging to SQLite (accountability)
    - Safe subprocess execution (no shell injection)
    - Ethical disclaimer enforcement
    - Scope-of-work validation
    - Structured output formatting
    """

    def __init__(self, config: Dict[str, Any], db_path: str = "logs/scans.db"):
        """
        Initialize the base agent.

        Args:
            config: Agent configuration dictionary (from config.yaml)
            db_path: Path to the SQLite audit log database
        """
        self.config = config
        self.db_path = db_path
        self.logger = logging.getLogger(self.__class__.__name__)
        self.findings: list = []  # Accumulated findings for report generation
        self._init_db()

    # ─── Database Initialization ───────────────────────────────────────────

    def _init_db(self):
        """Create the SQLite audit log database and table if they don't exist."""
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS scan_log (
                        id          INTEGER PRIMARY KEY AUTOINCREMENT,
                        timestamp   TEXT NOT NULL,
                        agent       TEXT NOT NULL,
                        target      TEXT NOT NULL,
                        command     TEXT,
                        result      TEXT,
                        status      TEXT DEFAULT 'success'
                    )
                """)
                conn.commit()
        except sqlite3.Error as e:
            self.logger.error(f"DB init error: {e}")

    def _log_to_db(self, target: str, command: str, result: str, status: str = "success"):
        """
        Log every command execution to the SQLite audit database.
        This is a standard practice in professional penetration testing frameworks.

        Args:
            target: The scan target (domain/IP)
            command: The command or action executed
            result: The output or result summary
            status: 'success', 'error', or 'skipped'
        """
        timestamp = datetime.datetime.utcnow().isoformat()
        agent_name = self.__class__.__name__
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute(
                    "INSERT INTO scan_log (timestamp, agent, target, command, result, status) "
                    "VALUES (?, ?, ?, ?, ?, ?)",
                    (timestamp, agent_name, target, command, result[:2000], status)
                )
                conn.commit()
        except sqlite3.Error as e:
            self.logger.error(f"DB log error: {e}")

    # ─── Safe Command Execution ────────────────────────────────────────────

    def run_command(
        self,
        command: list[str],
        target: str,
        timeout: int = 60,
        require_confirmation: bool = False,
        confirmation_message: Optional[str] = None,
    ) -> str:
        """
        Execute an external tool command safely.

        Uses shlex / list-based arguments to PREVENT shell injection.
        Never uses shell=True with user-supplied strings.

        Args:
            command: Command as a list of strings (e.g., ["nmap", "-sV", "target.com"])
            target: Target being scanned (for logging)
            timeout: Max seconds to wait for command
            require_confirmation: If True, prompt user before running
            confirmation_message: Custom message for confirmation prompt

        Returns:
            Command stdout output as string, or error message
        """
        # Safety: validate no shell metacharacters in individual args
        safe_command = [self._sanitize_arg(arg) for arg in command]
        cmd_str = " ".join(safe_command)

        # Ethical loop: ask user before aggressive operations
        if require_confirmation:
            msg = confirmation_message or f"This will run: {cmd_str}\nagainst target: {target}"
            print(f"\n[⚠️  SAFETY CHECK]\n{msg}")
            confirm = input("Type 'YES' to proceed, anything else to cancel: ").strip()
            if confirm != "YES":
                self._log_to_db(target, cmd_str, "User cancelled", "skipped")
                return "[Scan cancelled by user]"

        self.logger.info(f"Running: {cmd_str}")
        self._log_to_db(target, cmd_str, "started", "running")

        try:
            result = subprocess.run(
                safe_command,
                capture_output=True,
                text=True,
                timeout=timeout,
                # NEVER use shell=True with user input — prevents injection
            )
            output = result.stdout or result.stderr or "(no output)"
            self._log_to_db(target, cmd_str, output, "success" if result.returncode == 0 else "error")
            return output
        except FileNotFoundError:
            msg = f"Tool not found: '{safe_command[0]}'. Please install it first."
            self._log_to_db(target, cmd_str, msg, "error")
            return msg
        except subprocess.TimeoutExpired:
            msg = f"Command timed out after {timeout}s: {cmd_str}"
            self._log_to_db(target, cmd_str, msg, "error")
            return msg
        except Exception as e:
            msg = f"Command error: {e}"
            self._log_to_db(target, cmd_str, msg, "error")
            return msg

    @staticmethod
    def _sanitize_arg(arg: str) -> str:
        """
        Sanitize a single command argument.
        Strips dangerous shell metacharacters to prevent injection.
        Note: Since we never use shell=True, this is defense-in-depth.

        Args:
            arg: Single command argument string

        Returns:
            Sanitized argument string
        """
        # Characters that could cause issues even in list-form on some systems
        dangerous = [';', '&&', '||', '`', '$', '>', '<', '|', '\n', '\r']
        sanitized = arg
        for char in dangerous:
            sanitized = sanitized.replace(char, '')
        return sanitized.strip()

    # ─── Output Formatting ─────────────────────────────────────────────────

    def format_output(self, title: str, content: str, include_disclaimer: bool = True) -> str:
        """
        Format agent output with consistent styling.

        Args:
            title: Section title
            content: Main output content
            include_disclaimer: Whether to append ethical disclaimer

        Returns:
            Formatted output string
        """
        separator = "═" * 60
        output = f"\n{separator}\n  0xFlux4hm AI | {title}\n{separator}\n{content}"
        if include_disclaimer:
            output += ETHICAL_DISCLAIMER
        return output

    def add_finding(self, severity: str, title: str, description: str, target: str):
        """
        Add a finding to the accumulated findings list (used by report agent).

        Args:
            severity: 'Critical', 'High', 'Medium', 'Low', or 'Informational'
            title: Short finding title
            description: Detailed finding description
            target: Affected target
        """
        self.findings.append({
            "severity": severity,
            "title": title,
            "description": description,
            "target": target,
            "timestamp": datetime.datetime.utcnow().isoformat(),
            "agent": self.__class__.__name__,
        })

    # ─── Tool Availability Check ───────────────────────────────────────────

    @staticmethod
    def tool_available(tool_name: str) -> bool:
        """
        Check if an external tool is available on the system PATH.

        Args:
            tool_name: Tool binary name (e.g., 'nmap', 'subfinder')

        Returns:
            True if tool is found, False otherwise
        """
        import shutil
        return shutil.which(tool_name) is not None

    # ─── Abstract Interface ────────────────────────────────────────────────

    @abc.abstractmethod
    def run(self, target: str, options: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Execute the agent's primary task.

        Args:
            target: Target domain, IP, or URL
            options: Optional agent-specific options

        Returns:
            Dictionary with keys: 'success', 'output', 'findings', 'raw_data'
        """
        pass

    def _result(self, success: bool, output: str, raw_data: Any = None) -> Dict[str, Any]:
        """Helper to return a standardized result dict."""
        return {
            "success": success,
            "output": output,
            "findings": self.findings,
            "raw_data": raw_data,
            "agent": self.__class__.__name__,
        }
