"""
agents/report_agent.py
0xFlux4hm AI — VulnAgentRouter

Report Agent: Aggregates findings from all other agents and generates a
professional penetration testing report in Markdown and/or HTML format.
Includes executive summary, risk ratings, and clear recommendations.

⚠️  THIS IS FOR EDUCATIONAL USE AND AUTHORIZED TESTING ONLY.
"""

import datetime
import os
import json
import re
from typing import Optional, Dict, Any, List

from agents.base_agent import BaseAgent

# ── Risk Severity Colors (for HTML report) ────────────────────────────────────
SEVERITY_COLORS = {
    "Critical": "#dc2626",   # Red
    "High":     "#ea580c",   # Orange
    "Medium":   "#ca8a04",   # Yellow
    "Low":      "#16a34a",   # Green
    "Informational": "#2563eb",  # Blue
}

SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Informational"]

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>0xFlux4hm AI — Pentest Report: {target}</title>
<style>
  :root {{
    --bg: #0f172a; --surface: #1e293b; --border: #334155;
    --text: #e2e8f0; --accent: #38bdf8; --muted: #94a3b8;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif;
          line-height: 1.7; padding: 2rem; }}
  .container {{ max-width: 960px; margin: 0 auto; }}
  .header {{ border-bottom: 2px solid var(--accent); padding-bottom: 1.5rem; margin-bottom: 2rem; }}
  .brand {{ font-size: 0.85rem; color: var(--accent); font-family: monospace; letter-spacing: 2px;
             text-transform: uppercase; margin-bottom: 0.5rem; }}
  h1 {{ font-size: 2rem; font-weight: 700; margin-bottom: 0.5rem; }}
  .meta {{ color: var(--muted); font-size: 0.9rem; }}
  .disclaimer {{ background: #7c1d1d; border: 1px solid #dc2626; border-radius: 8px;
                  padding: 1rem 1.5rem; margin: 1.5rem 0; font-size: 0.9rem; }}
  .disclaimer strong {{ color: #fca5a5; }}
  .exec-summary {{ background: var(--surface); border: 1px solid var(--border);
                    border-radius: 8px; padding: 1.5rem; margin: 1.5rem 0; }}
  h2 {{ font-size: 1.4rem; color: var(--accent); margin: 2rem 0 1rem; border-bottom: 1px solid var(--border);
         padding-bottom: 0.5rem; }}
  h3 {{ font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }}
  .risk-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
                 gap: 1rem; margin: 1rem 0; }}
  .risk-card {{ background: var(--surface); border-radius: 8px; padding: 1rem;
                 text-align: center; border: 1px solid var(--border); }}
  .risk-card .count {{ font-size: 2.5rem; font-weight: 700; }}
  .risk-card .label {{ font-size: 0.8rem; color: var(--muted); text-transform: uppercase;
                        letter-spacing: 1px; margin-top: 0.25rem; }}
  .finding {{ background: var(--surface); border-left: 4px solid; border-radius: 0 8px 8px 0;
               padding: 1rem 1.5rem; margin: 1rem 0; }}
  .finding-header {{ display: flex; justify-content: space-between; align-items: center;
                      margin-bottom: 0.5rem; }}
  .finding-title {{ font-weight: 600; font-size: 1rem; }}
  .badge {{ padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.75rem;
             font-weight: 700; color: white; text-transform: uppercase; }}
  .finding-meta {{ font-size: 0.8rem; color: var(--muted); margin-bottom: 0.5rem; }}
  .finding-desc {{ font-size: 0.9rem; color: var(--text); }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }}
  th {{ background: var(--surface); padding: 0.75rem; text-align: left;
         border-bottom: 2px solid var(--border); color: var(--accent); }}
  td {{ padding: 0.75rem; border-bottom: 1px solid var(--border); }}
  code {{ background: var(--surface); padding: 0.1rem 0.4rem; border-radius: 3px;
           font-family: monospace; font-size: 0.85rem; color: var(--accent); }}
  .footer {{ margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid var(--border);
              color: var(--muted); font-size: 0.8rem; text-align: center; }}
  ul {{ padding-left: 1.5rem; }}
  li {{ margin: 0.3rem 0; }}
  p {{ margin: 0.75rem 0; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <div class="brand">0xFlux4hm AI // VulnAgentRouter</div>
    <h1>Penetration Test Report</h1>
    <div class="meta">
      <strong>Target:</strong> {target} &nbsp;|&nbsp;
      <strong>Date:</strong> {date} &nbsp;|&nbsp;
      <strong>Classification:</strong> CONFIDENTIAL
    </div>
  </div>

  <div class="disclaimer">
    <strong>⚠️ AUTHORIZED USE ONLY</strong><br>
    This report was generated by 0xFlux4hm AI for educational purposes and
    authorized security testing only. Unauthorized use of this information
    against systems without explicit written permission is illegal.
    The user is solely responsible for compliance with all applicable laws.
  </div>

  {body}

  <div class="footer">
    Generated by 0xFlux4hm AI — VulnAgentRouter &nbsp;|&nbsp;
    {date} &nbsp;|&nbsp;
    For educational and authorized testing purposes only.
  </div>
</div>
</body>
</html>"""


class ReportAgent(BaseAgent):
    """
    Report Agent for 0xFlux4hm AI.

    Aggregates findings from all agents and generates professional reports:
    - Executive summary with overall risk rating
    - Per-finding details with severity ratings
    - Recommendations table
    - Markdown (.md) and/or HTML output

    Designed to produce reports suitable for professional pentest engagements.
    """

    AGENT_NAME = "Report Agent"

    def run(self, target: str, options: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Generate a comprehensive penetration testing report.

        Args:
            target: Target that was assessed
            options: Dict with optional keys:
                     'findings' — list of finding dicts from other agents
                     'agent_outputs' — raw output strings from agents
                     'format' — 'markdown', 'html', or 'both' (default: 'markdown')
                     'tester_name' — name of the tester
                     'scope' — scope of engagement

        Returns:
            Standardized result dict with report paths
        """
        options = options or {}
        findings = options.get("findings", self.findings)
        agent_outputs = options.get("agent_outputs", {})
        output_format = options.get("format", self.config.get("output_format", "markdown"))
        tester_name = options.get("tester_name", "0xFlux4hm AI")
        scope = options.get("scope", f"Security assessment of {target}")

        print(f"\n[REPORT] 📄 Generating penetration test report for: {target}")
        print(f"[REPORT] Format: {output_format}")
        print(f"[REPORT] Total findings: {len(findings)}\n")

        date_str = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        date_file = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")

        # Calculate risk summary
        risk_summary = self._calculate_risk_summary(findings)
        overall_risk = self._calculate_overall_risk(risk_summary)

        # ── Build Markdown Report ────────────────────────────────────────────
        md_content = self._build_markdown_report(
            target, date_str, findings, risk_summary,
            overall_risk, agent_outputs, scope, tester_name
        )

        saved_paths = {}

        # Save Markdown
        if output_format in ("markdown", "both"):
            md_path = self._save_markdown(target, date_file, md_content)
            saved_paths["markdown"] = md_path
            print(f"[REPORT] ✅ Markdown report: {md_path}")

        # Save HTML
        if output_format in ("html", "both"):
            html_content = self._build_html_report(
                target, date_str, findings, risk_summary,
                overall_risk, scope, tester_name
            )
            html_path = self._save_html(target, date_file, html_content)
            saved_paths["html"] = html_path
            print(f"[REPORT] ✅ HTML report: {html_path}")

        self._log_to_db(
            target,
            f"generate_report format={output_format}",
            f"findings={len(findings)}, risk={overall_risk}"
        )

        formatted_output = self.format_output(
            f"Report Generated — {target}",
            f"Overall Risk: **{overall_risk}**\n"
            f"Total Findings: {len(findings)}\n"
            f"Reports saved:\n" +
            "\n".join(f"  - {k}: {v}" for k, v in saved_paths.items()),
            include_disclaimer=True
        )

        print(f"\n[REPORT] 🎯 Overall Risk Rating: {overall_risk}")

        return self._result(True, formatted_output, {
            "report_paths": saved_paths,
            "overall_risk": overall_risk,
            "risk_summary": risk_summary,
            "finding_count": len(findings),
        })

    # ─── Report Building ───────────────────────────────────────────────────

    def _build_markdown_report(
        self, target: str, date_str: str, findings: List[Dict],
        risk_summary: Dict, overall_risk: str,
        agent_outputs: Dict, scope: str, tester_name: str
    ) -> str:
        """Build the full Markdown report content."""
        lines = [
            "# Penetration Test Report",
            "",
            "> **CONFIDENTIAL — AUTHORIZED USE ONLY**",
            "",
            "---",
            "",
            "## Report Information",
            "",
            f"| Field | Details |",
            f"|---|---|",
            f"| **Target** | `{target}` |",
            f"| **Assessment Date** | {date_str} |",
            f"| **Generated By** | {tester_name} (0xFlux4hm AI) |",
            f"| **Scope** | {scope} |",
            f"| **Overall Risk** | **{overall_risk}** |",
            f"| **Total Findings** | {len(findings)} |",
            "",
            "---",
            "",
        ]

        # Disclaimer
        lines += [
            "## ⚠️ Disclaimer",
            "",
            "This report was generated by **0xFlux4hm AI — VulnAgentRouter** for "
            "**educational purposes and authorized security testing only**. "
            "Unauthorized use of this information against systems without explicit "
            "written permission is illegal and may violate applicable laws including "
            "the CFAA, UK Computer Misuse Act, and equivalent legislation. "
            "The user is solely responsible for compliance with all applicable laws.",
            "",
            "---",
            "",
        ]

        # Executive Summary
        lines += self._build_exec_summary_md(target, findings, risk_summary, overall_risk)

        # Risk Summary Table
        lines += self._build_risk_summary_md(risk_summary)

        # Detailed Findings
        lines += self._build_findings_md(findings)

        # Recommendations
        lines += self._build_recommendations_md(findings)

        # Raw Agent Output (appendix)
        if agent_outputs:
            lines += ["## Appendix: Raw Agent Output", ""]
            for agent_name, output in agent_outputs.items():
                lines += [
                    f"### {agent_name}",
                    "```",
                    str(output)[:2000],
                    "```",
                    "",
                ]

        return "\n".join(lines)

    def _build_exec_summary_md(
        self, target: str, findings: List[Dict],
        risk_summary: Dict, overall_risk: str
    ) -> List[str]:
        """Build executive summary section."""
        critical = risk_summary.get("Critical", 0)
        high = risk_summary.get("High", 0)
        medium = risk_summary.get("Medium", 0)

        summary_text = (
            f"A security assessment of **{target}** was conducted using 0xFlux4hm AI. "
            f"The assessment identified **{len(findings)} finding(s)** across multiple categories."
        )

        if critical > 0 or high > 0:
            summary_text += (
                f" **Immediate attention is required** for the "
                f"{critical} Critical and {high} High severity finding(s) discovered."
            )
        elif medium > 0:
            summary_text += (
                f" Medium severity issues were identified that should be addressed "
                f"in the near term as part of routine security maintenance."
            )
        else:
            summary_text += (
                " No critical or high severity issues were identified in the current assessment scope."
            )

        return [
            "## Executive Summary",
            "",
            summary_text,
            "",
            f"**Overall Risk Rating: {overall_risk}**",
            "",
        ]

    def _build_risk_summary_md(self, risk_summary: Dict) -> List[str]:
        """Build risk summary table."""
        lines = [
            "## Risk Summary",
            "",
            "| Severity | Count |",
            "|---|---|",
        ]
        for sev in SEVERITY_ORDER:
            count = risk_summary.get(sev, 0)
            lines.append(f"| **{sev}** | {count} |")
        lines.append("")
        return lines

    def _build_findings_md(self, findings: List[Dict]) -> List[str]:
        """Build detailed findings section sorted by severity."""
        lines = ["## Detailed Findings", ""]

        if not findings:
            lines.append("*No findings recorded in this session.*")
            lines.append("")
            return lines

        # Sort by severity
        sev_rank = {s: i for i, s in enumerate(SEVERITY_ORDER)}
        sorted_findings = sorted(findings, key=lambda f: sev_rank.get(f.get("severity", "Low"), 99))

        for i, finding in enumerate(sorted_findings, 1):
            sev = finding.get("severity", "Informational")
            title = finding.get("title", "Untitled Finding")
            desc = finding.get("description", "No description provided")
            target = finding.get("target", "")
            agent = finding.get("agent", "")
            timestamp = finding.get("timestamp", "")[:19].replace("T", " ")

            lines += [
                f"### Finding {i}: {title}",
                "",
                f"| Field | Value |",
                f"|---|---|",
                f"| **Severity** | **{sev}** |",
                f"| **Target** | `{target}` |",
                f"| **Source Agent** | {agent} |",
                f"| **Discovered** | {timestamp} |",
                "",
                "**Description:**",
                f"{desc}",
                "",
                "**Recommendation:**",
                f"{self._get_recommendation(title, desc)}",
                "",
                "---",
                "",
            ]

        return lines

    def _build_recommendations_md(self, findings: List[Dict]) -> List[str]:
        """Build a consolidated recommendations section."""
        lines = [
            "## Recommendations Summary",
            "",
            "| Priority | Finding | Recommendation |",
            "|---|---|---|",
        ]

        sev_rank = {s: i for i, s in enumerate(SEVERITY_ORDER)}
        sorted_findings = sorted(
            [f for f in findings if f.get("severity") in ("Critical", "High", "Medium")],
            key=lambda f: sev_rank.get(f.get("severity", "Low"), 99)
        )

        if not sorted_findings:
            lines = [
                "## Recommendations",
                "",
                "- Maintain current security posture with regular assessments.",
                "- Continue monitoring for new vulnerabilities in deployed services.",
                "- Implement a formal vulnerability management program.",
                "",
            ]
            return lines

        for finding in sorted_findings:
            sev = finding.get("severity", "")
            title = finding.get("title", "")[:50]
            rec = self._get_recommendation(title, finding.get("description", ""))[:80]
            lines.append(f"| {sev} | {title} | {rec} |")

        lines.append("")
        lines += [
            "### General Security Recommendations",
            "",
            "1. **Patch Management** — Apply all security patches promptly, prioritizing Critical/High CVEs.",
            "2. **Security Headers** — Implement all recommended HTTP security headers.",
            "3. **Input Validation** — Enforce strict input validation and output encoding throughout.",
            "4. **Least Privilege** — Apply the principle of least privilege to all services and accounts.",
            "5. **Monitoring** — Enable centralized logging and real-time alerting.",
            "6. **Regular Assessments** — Schedule periodic authorized security assessments.",
            "",
        ]

        return lines

    # ─── HTML Report Building ──────────────────────────────────────────────

    def _build_html_report(
        self, target: str, date_str: str, findings: List[Dict],
        risk_summary: Dict, overall_risk: str, scope: str, tester_name: str
    ) -> str:
        """Build the HTML report body and inject into the template."""
        body_parts = []

        # Executive Summary
        critical = risk_summary.get("Critical", 0)
        high = risk_summary.get("High", 0)
        body_parts.append(f"""
  <div class="exec-summary">
    <h2 style="margin-top:0; border:none;">Executive Summary</h2>
    <p>A security assessment of <code>{target}</code> was conducted using 0xFlux4hm AI.
    {len(findings)} finding(s) were identified. Overall risk: <strong>{overall_risk}</strong>.</p>
    {"<p><strong>⚠️ Immediate remediation required for Critical/High findings.</strong></p>" if (critical + high) > 0 else ""}
  </div>""")

        # Risk Cards
        body_parts.append('<h2>Risk Summary</h2><div class="risk-grid">')
        for sev in SEVERITY_ORDER:
            count = risk_summary.get(sev, 0)
            color = SEVERITY_COLORS.get(sev, "#666")
            body_parts.append(f"""
    <div class="risk-card" style="border-color:{color}">
      <div class="count" style="color:{color}">{count}</div>
      <div class="label">{sev}</div>
    </div>""")
        body_parts.append('</div>')

        # Findings
        body_parts.append('<h2>Detailed Findings</h2>')
        if not findings:
            body_parts.append('<p><em>No findings recorded in this session.</em></p>')
        else:
            sev_rank = {s: i for i, s in enumerate(SEVERITY_ORDER)}
            sorted_findings = sorted(findings, key=lambda f: sev_rank.get(f.get("severity", "Low"), 99))
            for i, finding in enumerate(sorted_findings, 1):
                sev = finding.get("severity", "Informational")
                title = finding.get("title", "Untitled")
                desc = finding.get("description", "")
                color = SEVERITY_COLORS.get(sev, "#666")
                rec = self._get_recommendation(title, desc)
                body_parts.append(f"""
    <div class="finding" style="border-left-color:{color}">
      <div class="finding-header">
        <span class="finding-title">Finding {i}: {title}</span>
        <span class="badge" style="background:{color}">{sev}</span>
      </div>
      <div class="finding-meta">Target: <code>{finding.get('target','')}</code> | Agent: {finding.get('agent','')}</div>
      <div class="finding-desc"><p><strong>Description:</strong> {desc}</p>
      <p><strong>Recommendation:</strong> {rec}</p></div>
    </div>""")

        # Recommendations Table
        body_parts.append("""
  <h2>Recommendations</h2>
  <table>
    <tr><th>Priority</th><th>Finding</th><th>Action</th></tr>""")

        actionable = [f for f in findings if f.get("severity") in ("Critical", "High", "Medium")]
        if actionable:
            sev_rank = {s: i for i, s in enumerate(SEVERITY_ORDER)}
            for f in sorted(actionable, key=lambda x: sev_rank.get(x.get("severity", "Low"), 99)):
                sev = f.get("severity", "")
                color = SEVERITY_COLORS.get(sev, "#666")
                body_parts.append(
                    f'<tr><td><span class="badge" style="background:{color}">{sev}</span></td>'
                    f'<td>{f.get("title","")[:60]}</td>'
                    f'<td>{self._get_recommendation(f.get("title",""), f.get("description",""))[:100]}</td></tr>'
                )
        else:
            body_parts.append('<tr><td colspan="3">No critical/high/medium findings — maintain security posture.</td></tr>')

        body_parts.append('</table>')

        body = "\n".join(body_parts)
        return HTML_TEMPLATE.format(target=target, date=date_str, body=body)

    # ─── Utility ───────────────────────────────────────────────────────────

    @staticmethod
    def _get_recommendation(title: str, description: str) -> str:
        """Generate a contextual recommendation based on finding title/description."""
        combined = (title + " " + description).lower()
        if any(k in combined for k in ["sqli", "sql injection", "sql error"]):
            return "Implement parameterized queries. Apply input validation and WAF rules."
        elif any(k in combined for k in ["xss", "cross-site scripting", "reflected"]):
            return "Implement Content Security Policy. Encode all user-supplied output."
        elif any(k in combined for k in ["header", "hsts", "csp", "x-frame"]):
            return "Configure missing security headers in web server / application settings."
        elif any(k in combined for k in ["port", "service", "open"]):
            return "Close unnecessary ports. Apply firewall rules. Update service software."
        elif any(k in combined for k in ["subdomain", "enumeration"]):
            return "Audit all subdomains. Disable unused subdomains. Apply same security standards to all."
        elif any(k in combined for k in ["cve", "exploit", "vulnerability"]):
            return "Apply vendor security patch immediately. Check NVD for patch details."
        elif any(k in combined for k in ["server", "disclosure", "powered-by"]):
            return "Remove or suppress version/technology disclosure headers."
        else:
            return "Review finding, apply principle of least privilege, and follow vendor guidance."

    @staticmethod
    def _calculate_risk_summary(findings: List[Dict]) -> Dict[str, int]:
        """Count findings by severity."""
        summary = {sev: 0 for sev in SEVERITY_ORDER}
        for finding in findings:
            sev = finding.get("severity", "Informational")
            if sev in summary:
                summary[sev] += 1
            else:
                summary["Informational"] += 1
        return summary

    @staticmethod
    def _calculate_overall_risk(risk_summary: Dict[str, int]) -> str:
        """Determine overall risk based on worst finding."""
        if risk_summary.get("Critical", 0) > 0:
            return "CRITICAL"
        elif risk_summary.get("High", 0) > 0:
            return "HIGH"
        elif risk_summary.get("Medium", 0) > 0:
            return "MEDIUM"
        elif risk_summary.get("Low", 0) > 0:
            return "LOW"
        else:
            return "INFORMATIONAL"

    def _save_markdown(self, target: str, date_str: str, content: str) -> str:
        """Save Markdown report."""
        os.makedirs("logs/reports", exist_ok=True)
        safe = re.sub(r"[^\w]", "_", target)[:40]
        path = f"logs/reports/report_{safe}_{date_str}.md"
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            return path
        except IOError as e:
            self.logger.error(f"Failed to save Markdown report: {e}")
            return ""

    def _save_html(self, target: str, date_str: str, content: str) -> str:
        """Save HTML report."""
        os.makedirs("logs/reports", exist_ok=True)
        safe = re.sub(r"[^\w]", "_", target)[:40]
        path = f"logs/reports/report_{safe}_{date_str}.html"
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            return path
        except IOError as e:
            self.logger.error(f"Failed to save HTML report: {e}")
            return ""
